/**
 * تسميات واجهة المستخدم
 */

// تسميات عامة
export const COMMON_LABELS = {
  FULL_NAME: 'الاسم الكامل',
  NATIONAL_ID: 'رقم الهوية الوطنية',
  PHONE: 'رقم الجوال',
  EMAIL: 'البريد الإلكتروني',
  PASSWORD: 'كلمة المرور',
  CONFIRM_PASSWORD: 'تأكيد كلمة المرور',
  BIRTH_DATE: 'تاريخ الميلاد',
  GENDER: 'الجنس',
  MALE: 'ذكر',
  FEMALE: 'أنثى',
  AGE: 'العمر',
  CITY: 'المدينة',
  ADDRESS: 'العنوان',
  POSTAL_CODE: 'الرمز البريدي',
  STATUS: 'الحالة',
  ACTIVE: 'نشط',
  INACTIVE: 'غير نشط',
  SUSPENDED: 'معلق',
  PENDING: 'قيد الانتظار',
  APPROVED: 'معتمد',
  REJECTED: 'مرفوض',
  CREATED_AT: 'تاريخ الإنشاء',
  UPDATED_AT: 'تاريخ التحديث',
  ACTIONS: 'الإجراءات',
  SEARCH: 'بحث',
  FILTER: 'تصفية',
  ALL: 'الكل',
  SAVE: 'حفظ',
  CANCEL: 'إلغاء',
  SUBMIT: 'إرسال',
  CLOSE: 'إغلاق',
  EDIT: 'تعديل',
  DELETE: 'حذف',
  VIEW: 'عرض',
  BACK: 'رجوع',
  NEXT: 'التالي',
  FINISH: 'إنهاء',
  CONTINUE: 'متابعة',
  REFRESH: 'تحديث',
  LOGIN: 'تسجيل الدخول',
  LOGOUT: 'تسجيل الخروج',
  REGISTER: 'تسجيل جديد'
};

// تسميات المستفيدين
export const BENEFICIARY_LABELS = {
  DISABILITY_TYPE: 'نوع الإعاقة',
  DISABILITY_DETAILS: 'تفاصيل الإعاقة',
  DISABILITY_CARD: 'بطاقة الإعاقة',
  DISABILITY_CARD_NUMBER: 'رقم بطاقة الإعاقة',
  DEAF: 'أصم',
  HEARING_IMPAIRED: 'ضعيف سمع',
  HEARING_LOSS: 'فاقد سمع',
  VISUAL_IMPAIRED: 'ضعيف بصر',
  BLIND: 'فاقد بصر',
  MOBILITY_IMPAIRED: 'إعاقة حركية',
  INTELLECTUAL_DISABILITY: 'إعاقة ذهنية',
  MULTIPLE_DISABILITIES: 'إعاقات متعددة',
  OTHER: 'أخرى',
  EDUCATION_LEVEL: 'المؤهل الدراسي',
  NO_EDUCATION: 'بدون تعليم',
  PRIMARY: 'ابتدائي',
  INTERMEDIATE: 'متوسط',
  SECONDARY: 'ثانوي',
  DIPLOMA: 'دبلوم',
  BACHELOR: 'بكالوريوس',
  MASTER: 'ماجستير',
  PHD: 'دكتوراه',
  EMPLOYMENT_STATUS: 'الحالة الوظيفية',
  UNEMPLOYED: 'عاطل عن العمل',
  EMPLOYED: 'موظف',
  RETIRED: 'متقاعد',
  STUDENT: 'طالب',
  DISABLED_UNABLE_WORK: 'غير قادر على العمل بسبب الإعاقة',
  MONTHLY_INCOME: 'الدخل الشهري',
  BENEFICIARY_PROFILE: 'ملف المستفيد',
  MEMBERSHIP_NUMBER: 'رقم العضوية',
  MEMBERSHIP_STATUS: 'حالة العضوية',
  REGISTRATION_DATE: 'تاريخ التسجيل',
  PREFERRED_BRANCH: 'الفرع المفضل',
  REGISTRATION_STATUS: 'حالة التسجيل',
  PROFILE_COMPLETION: 'اكتمال الملف'
};

// تسميات الطلبات
export const REQUEST_LABELS = {
  REQUEST_NUMBER: 'رقم الطلب',
  REQUEST_DATE: 'تاريخ الطلب',
  REQUEST_STATUS: 'حالة الطلب',
  SERVICE_NAME: 'اسم الخدمة',
  REQUESTED_AMOUNT: 'المبلغ المطلوب',
  APPROVED_AMOUNT: 'المبلغ المعتمد',
  REQUEST_REASON: 'سبب الطلب',
  REJECTION_REASON: 'سبب الرفض',
  ADDITIONAL_NOTES: 'ملاحظات إضافية',
  PENDING: 'قيد الانتظار',
  UNDER_REVIEW: 'قيد المراجعة',
  APPROVED: 'تمت الموافقة',
  REJECTED: 'مرفوض',
  CANCELLED: 'ملغي',
  COMPLETED: 'مكتمل',
  ON_HOLD: 'معلق',
  EXPIRY_DATE: 'تاريخ الانتهاء',
  PROCESSED_BY: 'تمت المعالجة بواسطة',
  PROCESSED_DATE: 'تاريخ المعالجة',
  PRIORITY: 'الأولوية',
  HIGH: 'عالية',
  MEDIUM: 'متوسطة',
  LOW: 'منخفضة',
  REQUEST_TIMELINE: 'مسار الطلب الزمني',
  LAST_UPDATE: 'آخر تحديث',
  VERIFICATION_STATUS: 'حالة التحقق'
};

// تسميات المستندات
export const DOCUMENT_LABELS = {
  DOCUMENT_NAME: 'اسم المستند',
  DOCUMENT_TYPE: 'نوع المستند',
  UPLOAD_DATE: 'تاريخ الرفع',
  FILE_SIZE: 'حجم الملف',
  FILE_TYPE: 'نوع الملف',
  UPLOADED_BY: 'تم الرفع بواسطة',
  VERIFIED_BY: 'تم التحقق بواسطة',
  VERIFICATION_DATE: 'تاريخ التحقق',
  VERIFICATION_STATUS: 'حالة التحقق',
  VERIFICATION_NOTES: 'ملاحظات التحقق',
  PENDING: 'قيد التحقق',
  VERIFIED: 'تم التحقق',
  REJECTED: 'مرفوض',
  NEEDS_REPLACEMENT: 'يحتاج استبدال',
  UPLOAD_DOCUMENT: 'رفع مستند',
  CHOOSE_FILE: 'اختر ملف',
  REPLACE_DOCUMENT: 'استبدال المستند',
  VIEW_DOCUMENT: 'عرض المستند',
  DOCUMENT_REQUIREMENTS: 'متطلبات المستند'
};

// تسميات الفروع
export const BRANCH_LABELS = {
  BRANCH_NAME: 'اسم الفرع',
  BRANCH_CITY: 'المدينة',
  BRANCH_ADDRESS: 'العنوان',
  BRANCH_PHONE: 'رقم الهاتف',
  BRANCH_MANAGER: 'مدير الفرع',
  BRANCH_EMPLOYEES: 'عدد الموظفين',
  BRANCH_MEMBERS: 'عدد المستفيدين',
  BRANCH_STATUS: 'حالة الفرع',
  ACTIVE: 'نشط',
  INACTIVE: 'غير نشط',
  CREATION_DATE: 'تاريخ الإنشاء',
  LAST_UPDATE: 'آخر تحديث',
  BRANCH_STATS: 'إحصائيات الفرع',
  PENDING_REGISTRATIONS: 'طلبات التسجيل قيد المراجعة',
  ACTIVE_REQUESTS: 'الطلبات النشطة',
  BRANCH_RANK: 'ترتيب الفرع'
};

// تسميات الخدمات
export const SERVICE_LABELS = {
  SERVICE_NAME: 'اسم الخدمة',
  SERVICE_DESCRIPTION: 'وصف الخدمة',
  SERVICE_CATEGORY: 'فئة الخدمة',
  REQUIREMENTS: 'المتطلبات',
  SERVICE_REQUIREMENTS: 'متطلبات الخدمة',
  REQUIRED_DOCUMENTS: 'المستندات المطلوبة',
  MAX_AMOUNT: 'الحد الأقصى للمبلغ',
  DURATION_DAYS: 'المدة بالأيام',
  SERVICE_CREATOR: 'منشئ الخدمة',
  SERVICE_STATUS: 'حالة الخدمة',
  ACTIVE: 'نشطة',
  INACTIVE: 'غير نشطة',
  REAPPLICATION_PERIOD: 'فترة إعادة التقديم',
  ONE_TIME_ONLY: 'مرة واحدة فقط',
  AVAILABLE_AFTER: 'متاحة بعد',
  REQUESTS_COUNT: 'عدد الطلبات',
  SERVICE_STATS: 'إحصائيات الخدمة',
  APPROVAL_RATE: 'معدل الموافقة',
  REJECTION_RATE: 'معدل الرفض',
  AVERAGE_PROCESSING_TIME: 'متوسط وقت المعالجة'
};

// تسميات المستخدمين
export const USER_LABELS = {
  USER_DETAILS: 'تفاصيل المستخدم',
  USER_NAME: 'اسم المستخدم',
  USER_ROLE: 'دور المستخدم',
  USER_STATUS: 'حالة المستخدم',
  USER_BRANCH: 'الفرع',
  USER_CREATION_DATE: 'تاريخ الإنشاء',
  USER_LAST_LOGIN: 'آخر تسجيل دخول',
  ACTIVE: 'نشط',
  INACTIVE: 'غير نشط',
  ADMIN: 'مدير النظام',
  BRANCH_MANAGER: 'مدير فرع',
  EMPLOYEE: 'موظف',
  BENEFICIARY: 'مستفيد',
  RESET_PASSWORD: 'إعادة تعيين كلمة المرور',
  PASSWORD_REQUIREMENTS: 'متطلبات كلمة المرور',
  CHANGE_ROLE: 'تغيير الدور',
  ASSIGN_TO_BRANCH: 'تعيين الفرع'
};

// تسميات التقارير
export const REPORT_LABELS = {
  REPORTS_ANALYTICS: 'التقارير والإحصائيات',
  USERS_REPORT: 'تقرير المستخدمين',
  BRANCHES_REPORT: 'تقرير الفروع',
  SERVICES_REPORT: 'تقرير الخدمات',
  PERFORMANCE_REPORT: 'تقرير الأداء',
  DAILY_REPORT: 'تقرير يومي',
  WEEKLY_REPORT: 'تقرير أسبوعي',
  MONTHLY_REPORT: 'تقرير شهري',
  YEARLY_REPORT: 'تقرير سنوي',
  CUSTOM_PERIOD: 'فترة مخصصة',
  FROM_DATE: 'من تاريخ',
  TO_DATE: 'إلى تاريخ',
  EXPORT_REPORT: 'تصدير التقرير',
  EXPORT_EXCEL: 'تصدير Excel',
  EXPORT_PDF: 'تصدير PDF',
  PRINT_REPORT: 'طباعة التقرير',
  REPORT_GENERATED_DATE: 'تاريخ إنشاء التقرير',
  GENERATED_BY: 'تم الإنشاء بواسطة'
};
